version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: olist_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: olist_gold
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - olist_network

  metabase:
    image: metabase/metabase:latest
    container_name: olist_bi
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - olist_network

networks:
  olist_network:
    driver: bridge

volumes:
  pgdata: